/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import Modelo.Inspector;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Paul
 */
public class Acceso_Inspector extends javax.swing.JFrame {
    
    Inspector datos=new Inspector("", 0, "", "");
    Controlador controlador=new Controlador();

    /**
     * Creates new form PRO
     */
    public Acceso_Inspector() {
        initComponents();
        
        controlador.Logueo(datos);
        
        txt_nombres.setText(datos.getNombres());
        txt_apellidos.setText(datos.getApellidos());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_registrarAlumno = new javax.swing.JToggleButton();
        btn_alumnosYcalificaciones = new javax.swing.JToggleButton();
        btn_cuadroGeneral = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_registrarAlumno.setBackground(new java.awt.Color(204, 204, 0));
        btn_registrarAlumno.setFont(new java.awt.Font("Eras Demi ITC", 2, 18)); // NOI18N
        btn_registrarAlumno.setForeground(new java.awt.Color(0, 0, 0));
        btn_registrarAlumno.setText("Registrar Alumno");
        btn_registrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarAlumnoActionPerformed(evt);
            }
        });

        btn_alumnosYcalificaciones.setBackground(new java.awt.Color(255, 0, 0));
        btn_alumnosYcalificaciones.setFont(new java.awt.Font("Eras Demi ITC", 2, 18)); // NOI18N
        btn_alumnosYcalificaciones.setForeground(new java.awt.Color(0, 0, 0));
        btn_alumnosYcalificaciones.setText("Alumnos y calificaciones");
        btn_alumnosYcalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alumnosYcalificacionesActionPerformed(evt);
            }
        });

        btn_cuadroGeneral.setBackground(new java.awt.Color(0, 153, 204));
        btn_cuadroGeneral.setFont(new java.awt.Font("Eras Demi ITC", 2, 18)); // NOI18N
        btn_cuadroGeneral.setForeground(new java.awt.Color(0, 0, 0));
        btn_cuadroGeneral.setText("Cuadro General");
        btn_cuadroGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cuadroGeneralActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bryan\\Documents\\GitHub\\Java\\Proyecto_Final\\src\\imagenes\\Registro.jpeg")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bryan\\Documents\\GitHub\\Java\\Proyecto_Final\\src\\imagenes\\Calificaciones.jpeg")); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bryan\\Documents\\GitHub\\Java\\Proyecto_Final\\src\\imagenes\\Cuadro General.jpeg")); // NOI18N

        txt_nombres.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txt_nombres.setText(".");

        txt_apellidos.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txt_apellidos.setText(".");

        btn_cancelar.setFont(new java.awt.Font("Engravers MT", 3, 18)); // NOI18N
        btn_cancelar.setText("SALIR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Elephant", 3, 36)); // NOI18N
        jLabel4.setText("BIENVENIDO ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btn_registrarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_alumnosYcalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(btn_cuadroGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(416, 416, 416))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3)
                        .addGap(34, 34, 34))))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txt_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_registrarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_alumnosYcalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cuadroGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(154, 154, 154)))
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarAlumnoActionPerformed
        IngresarAlumno ingreso=new IngresarAlumno();
        this.setVisible(false);
        ingreso.setVisible(true);
    }//GEN-LAST:event_btn_registrarAlumnoActionPerformed

    private void btn_cuadroGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cuadroGeneralActionPerformed
        
        Cuadro_General cuadro=new Cuadro_General();
        
        this.setVisible(false);
        cuadro.setVisible(true);
        
    }//GEN-LAST:event_btn_cuadroGeneralActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
       
        Inicio inicio=new Inicio();
        this.setVisible(false);
        inicio.setVisible(true);
        
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_alumnosYcalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alumnosYcalificacionesActionPerformed
        
     
            Alumnos_Calificaciones ac=new Alumnos_Calificaciones();
            this.setVisible(false);
            ac.setVisible(true);
        
        
    }//GEN-LAST:event_btn_alumnosYcalificacionesActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_alumnosYcalificaciones;
    private javax.swing.JToggleButton btn_cancelar;
    private javax.swing.JToggleButton btn_cuadroGeneral;
    private javax.swing.JToggleButton btn_registrarAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel txt_apellidos;
    private javax.swing.JLabel txt_nombres;
    // End of variables declaration//GEN-END:variables
}
