/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import Modelo.Alumno;
import Modelo.Notas;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Santiago
 */
public class Alumnos_Calificaciones extends javax.swing.JFrame {

    int cont = 0;
    DefaultTableModel modelo;
    Controlador controlador=new Controlador();
    Notas notas=new Notas();
    Alumno alumno=new Alumno( 0, "", "");
    
    
    
    /**
     * Creates new form Listado
     */
    public Alumnos_Calificaciones(){
        initComponents();
        
        txt_ci.setText("");
        
        controlador.obtenerDatos(notas);
        modelo = new DefaultTableModel(){@Override
        public boolean isCellEditable(int row, int column) {
				return false;
			}};
        tbl_Todo.setModel(modelo);
        
        modelo.addColumn("CI");
        modelo.addColumn("Inglés");
        modelo.addColumn("Lenguaje");
        modelo.addColumn("Fisica");
        modelo.addColumn("Matemática");
        modelo.addColumn("Química");
        modelo.addColumn("E.Física");
        modelo.addColumn("Geometría");
        modelo.addColumn("Computación");
        modelo.addColumn("Biología");
        modelo.addColumn("Anatomía");
        modelo.addColumn("Promedio");
        LlenarTabla();
    }
    
    public void LlenarTabla(){
        
        controlador.obtenerDatos(notas);
        
        Object []object = new Object[12];
        
        for (int i=0; i<notas.getCI().size(); i++){
                
                object[0] = notas.getCI().get(i);
                object[1] = notas.getIngles().get(i);
                object[2] = notas.getLenguaje().get(i);
                object[3] = notas.getFisica().get(i);
                object[4] = notas.getMatematica().get(i);
                object[5] = notas.getQuimica().get(i);
                object[6] = notas.getEfisica().get(i);
                object[7] = notas.getGeometria().get(i);
                object[8] = notas.getComputacion().get(i);
                object[9] = notas.getBiologia().get(i);
                object[10] = notas.getAnatomia().get(i);
                object[11] = notas.getPromedio().get(i);
                
                modelo.addRow(object);
                
        }     
                
        
        
    }
    
    public void VaciarTabla(){
        DefaultTableModel tb = (DefaultTableModel) tbl_Todo.getModel();
        int a = tbl_Todo.getRowCount()-1;
        for (int i = a; i >= 0; i--) {          
        tb.removeRow(tb.getRowCount()-1);
        }
        //cargaTicket();
    }
    
			
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ci = new javax.swing.JTextField();
        btn_filtro = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Todo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel1.setText("Alumnos Y Calificaciones");

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel2.setText("Número de Cédula :");

        txt_ci.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ciKeyTyped(evt);
            }
        });

        btn_filtro.setText("Filtrar");
        btn_filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filtroActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        tbl_Todo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Todo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbl_Todo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txt_ci, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(btn_filtro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(btn_regresar)
                        .addGap(134, 134, 134)
                        .addComponent(btn_eliminar)
                        .addGap(114, 114, 114)
                        .addComponent(btn_actualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btn_filtro))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_regresar)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_actualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
       
        int fila = tbl_Todo.getSelectedRow();
        if(fila != -1){
          
            controlador.Eliminar((int) modelo.getValueAt(fila, 0));
            
            modelo.removeRow(fila);
            
            JOptionPane.showMessageDialog(null, "Datos Eliminados", "Delete", 1);
            
        }else{
            JOptionPane.showMessageDialog(this,"Debe seleccionar una fila");
        }
        
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        
        Acceso_Inspector acceso=new Acceso_Inspector();
        
        this.setVisible(false);
        acceso.setVisible(true);
        
        cont=0;
        
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void txt_ciKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ciKeyTyped

        char car = evt.getKeyChar();
if(Character.isDigit(car) && cont<10){
    
    cont++;
        
}else{
evt.consume();
getToolkit().beep();
}  
        
    }//GEN-LAST:event_txt_ciKeyTyped

    private void btn_filtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filtroActionPerformed
       
        VaciarTabla();
        
        controlador.BuscarCI(notas,Integer.parseInt(txt_ci.getText()));
        
        Object []object = new Object[12];
        
        for (int i=0; i<notas.getCI().size(); i++){
                
                object[0] = notas.getCI().get(i);
                object[1] = notas.getIngles().get(i);
                object[2] = notas.getLenguaje().get(i);
                object[3] = notas.getFisica().get(i);
                object[4] = notas.getMatematica().get(i);
                object[5] = notas.getQuimica().get(i);
                object[6] = notas.getEfisica().get(i);
                object[7] = notas.getGeometria().get(i);
                object[8] = notas.getComputacion().get(i);
                object[9] = notas.getBiologia().get(i);
                object[10] = notas.getAnatomia().get(i);
                object[11] = notas.getPromedio().get(i);
                
                modelo.addRow(object);     
        }
        
    }//GEN-LAST:event_btn_filtroActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed

int fila = tbl_Todo.getSelectedRow();
        if(fila != -1){
            
            Actualizar actualizar=new Actualizar((int) modelo.getValueAt(fila, 0));
        
        this.setVisible(false);
        actualizar.setVisible(true);
        
        cont=0;
            
        }else{
            JOptionPane.showMessageDialog(this,"Debe seleccionar una fila");
        }        
        
        
    }//GEN-LAST:event_btn_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_filtro;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Todo;
    private javax.swing.JTextField txt_ci;
    // End of variables declaration//GEN-END:variables
}
